services:
  reactserver:
    build:
      context: .
      dockerfile: src/PokeGame.Core/dockerfile.react.server.local
    ports:
      - 8080:443
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/reactserverapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      Logging__LogLevel__Default: Debug
    volumes:
      - ./certs:/https:ro
